### ISSUE TITLE
About bigdata learn list.

### ISSUE THREAD

**Issue by Macroldj** [Macroldj/MacroData#18]
- [x] databases 
- [x] sql pro language
- [x] distributed storage distrubuted computer
- [x] process tools and language
- [x] analysis data tools

**Comment by macroldj** [comment]
databases : 
  - mysql  一般中小型企业的业务支撑数据库
  - mongodb  一般业务数据库
  - postgresql  一般用来当作数据仓库

**Comment by macroldj** [comment]
### sql
1.

**Comment by macroldj** [comment]
### hadoop
  -

**Comment by macroldj** [comment]
### spark
  -

**Comment by macroldj** [comment]
### java scala
  -

**Comment by macroldj** [comment]
### flink
  -
