### ISSUE TITLE
Research: python oprions mysql、mongodb and redis?

### ISSUE THREAD

**Issue by Macroldj** [Macroldj/MacroData#2]
- [x] python mysql
- [x] python mongodb
- [x] python redis

**Comment by macroldj** [comment]
# [关于mysql 数据库相关的操作](https://github.com/PyMySQL/PyMySQL)

**Comment by Macroldj** [comment]
`py
import pymysql
import pymongo
`
[mogodb python](https://juejin.im/post/5addbd0e518825671f2f62ee)

**Comment by Macroldj** [comment]
### redis
- [ ]  框架调用
  - [ ] [python-redis](https://django-redis-chs.readthedocs.io/zh_CN/latest/)
