### ISSUE TITLE
Learn postgresql 

### ISSUE THREAD

**Issue by Macroldj** [Macroldj/MacroData#9]
1. install and update postgresql
2. security user authentic 
3. CRUD option

**Comment by macroldj** [comment]
学习环境docker搭建。
[postgresql docker](https://hub.docker.com/_/postgres) 
```sh
docker run -it --rm --network some-network postgres psql -h some-postgres -U postgres
```

**Comment by Macroldj** [comment]
### Reference
- [ ] [www.postgresql.org](https://www.postgresql.org/docs/12/index.html)
